### ISSUE TITLE
Not an issue, just a question

### ISSUE THREAD

**Issue by petergilmour1987** [redxdev/ECS#14]
Awesome library. Works perfectly. I just have a question about general use. Should there be 1 global world or one in every scene? I have written a scene manager and i cant find an answer anywhere regarding this. I am leaning towards one for every scene..... but id love to hear how you use it. Thanks.

Sorry i know this is the wrong place to ask questions but i dont understand github.

**Comment by redxdev** [comment]
It's really up to you and what you mean by scenes. I'd generally expect there to only be a single world at any one time but whether you want the world to exist as a separate piece or as part of your "active" scene is completely up to your own designs.
