### ISSUE TITLE
Doesn't compile with gcc

### ISSUE THREAD

**Issue by hardliner66** [redxdev/ECS#2]
I tried to compile this on ubuntu with g++-4.8.4

Compiled with:
`g++ -std=c++11 sample.cpp`

I get the following errors:
[errors.txt](https://github.com/redxdev/ECS/files/861536/errors.txt)

**Comment by redxdev** [comment]
Hmm, I haven't tried compiling with GCC. I'll test it out and get back to you.

Yep, I'm getting the same on G++ 5.4.1. That's what I get for just testing on VS. I'll have this fixed soonish.

**Comment by redxdev** [comment]
The latest version should work fine on G++. I've tested on 5.4.1 but your version should work fine too.

**Comment by hardliner66** [comment]
Sorry, I missed the notification.

I can confirm that it works now. Thanks :)
