### ISSUE TITLE
Doesn't compile when included multiple times

### ISSUE THREAD

**Issue by konrad-kubacki** [redxdev/ECS#3]
Please, split source code to .hpp and .cpp OR make methods inline because there are linker errors when file is included more than once. Thank you.

**Comment by redxdev** [comment]
Will have this fixed in a bit.

**Comment by redxdev** [comment]
The latest commit should have this fixed. Please let me know if you are still having problems.

**Comment by konrad-kubacki** [comment]
It's working now, thank you!
